### ISSUE TITLE
New request: open the link by clicking

### ISSUE THREAD

**Issue by Sibojang9** [nobodxbodon/HistoryInThreads#2]
Now it opens the secondary link or does not do anything  once I click the link.  Hope to open the link directly in a new tab by clicking.

Thank you,

**Comment by Gitoffthelawn** [comment]
What do you mean by "secondary link"?

When I test this extension, clicking on a row has no effect.  I agree, it should open the selected item.

As to which tab to open it in, I recommend using Firefox's existing settings to determine whether to open it in the current tab versus a new tab.

**Comment by Sibojang9** [comment]
I mean that just by clicking a row, it should open that link. Thank you.

**Comment by Gitoffthelawn** [comment]
@sibojan I agree completely.

**Comment by nobodxbodon** [comment]
As I recall, I tried that before, and it was hard to expand a node (the triangle) without triggering clicking the row.

Plan: I'll try again, and if it's not that unusable, add a preference to the addon.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by nobodxbodon** [comment]
It should work in v2.1 now.
