### ISSUE TITLE
Cannot open any links

### ISSUE THREAD

**Issue by Gitoffthelawn** [nobodxbodon/HistoryInThreads#8]
In FF53, now cannot open any history links in the HistoryInThreads sidebar.

Site expansion works, but double-clicking does not open links.

**Comment by nobodxbodon** [comment]
IIRC double-clicking doesn't open link. I just tried with these methods to open link:
- The url can be opened in a new tab by just middle-click. 
- Right-click opens context menu, then "open link in new tab", or "switch to tab" if the url is already opened.

**Comment by Gitoffthelawn** [comment]
Thank you.  Hmmm... I thought single-click never worked, but double-click was supposed to work.  Perhaps I am remembering incorrectly.  But I thought double-clicking used to work as expected.

**Comment by nobodxbodon** [comment]
In v2.1, link is just like normal link in web page now, and can be opened in the same ways.
