### ISSUE TITLE
Update Version 1.10.3 in Firefox to "Works with Firefox 38.0a1 - 56.*"

### ISSUE THREAD

**Issue by sputnik1** [nobodxbodon/HistoryInThreads#9]
Version 1.10.3 is listed in Firefox as "Works with Firefox 38.0a1 - 43.0", so the "Add to Firefox" button is grayed-out. Users with Firefox >43.0 can't download it from the Add-Ons website. {Most don't know that the file can be downloaded here and edited to work.}  This is probably an incorrect entry, since Version 1.10.2 is listed in Firefox as "Works with Firefox 38.0a1 - 56.*"

Thanks for a great add-on. I'm looking forward to the port to WebExtensions if you can find the time to complete it.

**Comment by nobodxbodon** [comment]
Thanks a lot for the report and support! I just updated the compatibility.
And thanks for giving more motivation for porting (#6).
